pipeline:
  data_dir: "./data/raw"
  manifest_path: "./data/raw/manifest.json"
  generated_data_path: "./data/raw/generated_data.json" # Reverted back to the original .json name
  output_dir: "./output"

ray:
  num_cpus: 8
  address: "auto"

microservices:
  api_key: "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"
  data_designer_url: "https://localhost:8080/v1/nemo/dd"
  safe_synthesizer_url: "https://localhost:8080/v1/nemo/safe-synthesizer/validate"
  customizer_url: "https://localhost:8080/v1/nemo/customizer/lora"
  model: "nemotron-4-340b-instruct"